/**
 * The `dbrex` command.
 *
 * A shell shim rather than a symlink, because picking the interpreter is the
 * hard part. `nvm` commonly leaves `node` pointing at whatever version was
 * installed first — on this author's machine, Node 11 — which cannot run the
 * bundle at all, and `install-duckdb` additionally needs the `npm` that belongs
 * to the same version.
 *
 * So the shim finds a Node new enough, puts its directory first on PATH, and
 * only then runs the CLI. Written in POSIX sh so it does not itself depend on
 * anything being set up.
 */

/** Oldest Node the bundle is built for. */
export const MINIMUM_NODE_MAJOR = 18;

export function shimSource(cliPath: string): string {
  return `#!/bin/sh
# Generated by the DbRex extension. Safe to delete; it is written again on start.
set -e

want_major=${MINIMUM_NODE_MAJOR}

usable() {
  [ -x "$1" ] || return 1
  major=$("$1" -p 'process.versions.node.split(".")[0]' 2>/dev/null) || return 1
  [ "$major" -ge "$want_major" ] 2>/dev/null
}

node_bin=""

# 1. An explicit choice always wins.
if [ -n "\${DBREX_NODE:-}" ] && usable "$DBREX_NODE"; then
  node_bin="$DBREX_NODE"
fi

# 2. Whatever "node" means here, if it is new enough.
if [ -z "$node_bin" ]; then
  candidate=$(command -v node 2>/dev/null || true)
  if [ -n "$candidate" ] && usable "$candidate"; then
    node_bin="$candidate"
  fi
fi

# 3. The newest nvm install that is. Sorted by version, not by name.
if [ -z "$node_bin" ] && [ -d "$HOME/.nvm/versions/node" ]; then
  for candidate in $(ls -1 "$HOME/.nvm/versions/node" 2>/dev/null | sort -V -r); do
    if usable "$HOME/.nvm/versions/node/$candidate/bin/node"; then
      node_bin="$HOME/.nvm/versions/node/$candidate/bin/node"
      break
    fi
  done
fi

if [ -z "$node_bin" ]; then
  echo "dbrex: no Node $want_major or newer found." >&2
  echo "  Set DBREX_NODE to one, or install a current Node." >&2
  exit 127
fi

# npm has to come from the same install, or "install-duckdb" builds against the
# wrong interpreter.
PATH="$(dirname "$node_bin"):$PATH"
export PATH

exec "$node_bin" "${cliPath}" "$@"
`;
}
